### PR TITLE
🥅(common) deactivate logging anonymous user id error

### PR DESCRIPTION
**Pull request by sampaccoud**
This error is spamming our Sentry and doesn't help. Deactivating it and creating an issue to figure out what to do.

### CODE REVIEW

**Review by jmaupetit — APPROVED** [review]

**Comment by jmaupetit** [comment]
I think we should link the aforementioned issue in this PR.

**Review by rmoch — APPROVED** [review]
this will indeed fix the spam issue

**Comment by rmoch** [comment]
this gitmoji is not allowed 😱

**Pull request merged**
