### PR TITLE
Bump ORA2 version

### PR DESCRIPTION
**Pull request by bdero**
To include these changes:
- https://github.com/edx/edx-ora2/pull/1016
- https://github.com/edx/edx-ora2/pull/1017
- https://github.com/edx/edx-ora2/pull/1022

### CODE REVIEW

**Review by e-kolpakov — APPROVED** [review]

**Comment by bdero** [comment]
CC @jul - this is the ORA2 version bump to include the LaTeX fixes

**Comment by jul** [comment]
Sorry to interact so late. Does this includes the multi latex preview?

**Comment by jul** [comment]
PS job appreciated. Currently on staging and giving all satisfaction so far to our concerned users.
Keep up the good work.

**Comment by bdero** [comment]
> Does this includes the multi latex preview?

@jul Yup! It's includes the preview across all fields accepting LaTeX entry along with the fix for the LaTeX option in the studio ORA2 settings.

Thanks for taking a look!

**Comment by jul** [comment]
Hello deployed the bump ORA2 latex instead of my version.

Result: there is a conflict of version between ora2 latex multiple
preview and openedx platform on the dependency of path.py with our current version (7.2 vs 8.2.1)

testing fast that edx-plaftorm can be upgraded to 8.2.1 without harm.

**Comment by bdero** [comment]
@jul Ah, I actually ran into that same issue when I was testing it against a FUN box, but I neglected to include it. Sorry about that! The solution was indeed changing the required version in edx-platform to match ORA2. I then smoke tested the FUN box and was unable to find broken functionality as a result of the upgrade.

**Comment by jul** [comment]
No worry, it was easy to diagnose, fix and stage once again.
I just put a comment in case someone tripped on the same problem and needed the information.

**Pull request merged**
